sudo: required
dist: trusty
env:
  - VERSION_TAG=1.13.1
node_js:
- '8'
before_install:
- openssl enc -aes-256-cbc -d -K ${AES_KEY} -iv ${AES_IV} -in key.json.enc -out key.json
- cat key.json | docker login -u=_json_key --password-stdin https://gcr.io/
jobs:
  include:
    - stage: build image
      script:
        - docker build -t kickerd-nginx .
        - docker tag kickerd-nginx gcr.io/npm-image-registry-prod/npmjs/kickerd-nginx:latest
        - docker tag kickerd-nginx gcr.io/npm-image-registry-prod/npmjs/kickerd-nginx:$VERSION_TAG
        - docker push gcr.io/npm-image-registry-prod/npmjs/kickerd-nginx:latest
        - docker push gcr.io/npm-image-registry-prod/npmjs/kickerd-nginx:$VERSION_TAG
